# Generated by Django 2.2.14 on 2021-05-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_mourse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mourse',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterField(
            model_name='mourse',
            name='q_lectures',
            field=models.PositiveIntegerField(),
        ),
    ]
