# Generated by Django 2.2.14 on 2021-05-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_mourse', '0002_auto_20210502_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mourse',
            name='q_lectures',
            field=models.IntegerField(),
        ),
    ]
