# Generated by Django 2.2.14 on 2021-05-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_mourse', '0004_auto_20210502_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='mourse',
            name='n_lectures',
            field=models.PositiveIntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
    ]
