# Generated by Django 2.2.14 on 2021-05-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_mourse', '0005_mourse_n_lectures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mourse',
            name='n_lectures',
        ),
        migrations.AlterField(
            model_name='mourse',
            name='q_lectures',
            field=models.PositiveIntegerField(),
        ),
    ]
