# Generated by Django 2.2.14 on 2021-04-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_mourse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mourse',
            options={'ordering': ('start_date',)},
        ),
        migrations.AlterField(
            model_name='mourse',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
