# Generated by Django 2.2.14 on 2021-04-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_mourse', '0002_auto_20210428_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mourse',
            old_name='descr',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='mourse',
            name='end_date',
            field=models.DateField(blank=True, default='2021-12-25', null=True),
        ),
    ]
