# Generated by Django 2.2.14 on 2021-04-29 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_mourse', '0003_auto_20210429_0610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mourse',
            old_name='q_lections',
            new_name='q_lectures',
        ),
    ]
