# Generated by Django 3.2 on 2021-04-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_mourse', '0004_auto_20210429_0616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mourse',
            options={'ordering': ['start_date', 'author']},
        ),
        migrations.AddField(
            model_name='mourse',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mourse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
