# Generated by Django 2.2.14 on 2021-04-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_mourse', '0005_auto_20210429_0829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mourse',
            options={'ordering': ['-start_date']},
        ),
        migrations.RemoveField(
            model_name='mourse',
            name='slug',
        ),
        migrations.AlterField(
            model_name='mourse',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
